package com.docmind.api.shared.error;

public enum ApiErrorCode {
  AUTHENTICATION_REQUIRED,
  PERMISSION_DENIED,
  VALIDATION_FAILED,
  SCHEMA_INVALID,
  SENSITIVE_DATA_DETECTED,
  SENSITIVE_SCAN_UNAVAILABLE,
  UNKNOWN_SENSITIVE_TOKEN,
  FILE_TYPE_NOT_ALLOWED,
  FILE_TOO_LARGE,
  RESOURCE_NOT_FOUND,
  RESOURCE_CONFLICT,
  VERSION_CONFLICT,
  EDIT_LOCK_REQUIRED,
  EDIT_LOCK_CONFLICT,
  ANCHOR_STALE,
  IDEMPOTENCY_CONFLICT,
  TASK_FAILED,
  DEPENDENCY_UNAVAILABLE,
  RATE_LIMITED,
  INTERNAL_ERROR
}
